In [1]:
import numpy as np

### Задание 2.6.3

In [2]:
A = np.array([[1,2],[-3,1],[1,2],[1,-1]])
b = np.array([1,4,5,0]).reshape((4,1))

#### Задание 2.6.3_1
a) Вычислите матрицу Грама столбцов $ А : $ $A^{T}A =$

In [6]:
G = A.T @ A
G

array([[12,  0],
       [ 0, 10]])

#### Задание 2.6.3_2
b) $(A^{T}A)^{-1}$ имеет вид:

In [4]:
np.linalg.inv(G)

array([[0.08333333, 0.        ],
       [0.        , 0.1       ]])

#### Задание 2.6.3_3
с) $A^{T}\vec{b} =$ $ ?$  
Введите координаты полученного вектора через запятую (без пробела):


In [5]:
A.T @ b

array([[-6],
       [16]])

#### Задание 2.6.3_4
d) $\hat{w}= $  
Примечание: для корректого ответа НЕ округляйте $(A^{T}A)^{-1}$

Введите координаты полученного вектора через запятую (без пробела):

In [7]:
G = A.T @ A
(np.linalg.inv(G)) @ (A.T @ b)

array([[-0.5],
       [ 1.6]])

## 2.7. Классическая OLS линейная регрессия

### Задание 2.7.5
Используя данные, полученные нами в модуле ранее (см. таблицу и результат применения OLS к ней) сделайте прогноз типичной стоимости (в тыс. долларов) дома в городке с уровнем преступности $ CRIM = 0.2 $ и средним количеством комнат в доме $ RM = 6 $.

Прогноз стоимости:

Ответ округлите до тысячных

In [9]:
crim = 0.2
rm = 6

round(-29.3 - 0.26*crim + 8.4*rm,3)

21.048

## 2.9. Стандартизация признаков

### Задание 2.9.2

Стандартизируйте признак $x_1 = \left(\begin{array}{c} 
      11 \\
      8
    \end{array}\right)$ . Ответ округлите до сотых.  
Введите координты полученного вектора через запятую (без пробела):

In [117]:
x1 = np.array([11,8])
ans = (x1-x1.mean()) / np.linalg.norm(x1-x1.mean())
    
list(map(lambda x: round(x,2),ans))

[0.71, -0.71]

In [24]:
ans

array([ 0.70710678, -0.70710678])

## 2.11. --> Практика. Классический OLS алгоритм

In [28]:
# Загрузка библиотек
import numpy as np # для работы с массивами
import pandas as pd # для работы DataFrame 
import seaborn as sns # библиотека для визуализации статистических данных
import matplotlib.pyplot as plt # для построения графиков

%matplotlib inline

В датасете Admission_Predict_Ver1.1.csv находятся данные об абитуриентах и вероятности приёма их в магистратуру.

Целевой переменной является вероятность приёма в университет — Chance of Admit (ranging from 0 to 1 )

Признаки: 

1. GRE Scores ( out of 340 ) — баллы по GRE тестированию
2. TOEFL Scores ( out of 120 ) — баллы по экзамену TOEFL
3. University Rating ( out of 5 ) — рейтинг университета 
4. Statement of Purpose Strength ( out of 5 ) — весомость мотивационного письма
5. Letter of Recommendation Strength ( out of 5 ) — весомость рекомендационных писем
6. Undergraduate GPA ( out of 10 ) — средний балл в бакалавриате
7. Research Experience ( either 0 or 1 ) — наличие опыта исследовательской работы ( нет / есть)

In [32]:
df = pd.read_csv('./Unit3_data/Admission_Predict_Ver1.1.csv')

In [33]:
df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

### Задание 2.11.1
Сколько всего абитуриентов в выборке?

In [36]:
len(df)

500

### Задание 2.11.2
Составьте корреляциюнную матрицу перечисленных признаков вместе с целевой переменной, исключив столбец `Serial No.`

В поля для ответа впишите, округлив до двух знаков после точки:
корреляцию между `Chance of Admit` и `GRE Scores`

In [53]:
corr_matrix.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA',
       'Research', 'Chance of Admit '],
      dtype='object')

In [56]:
corr_matrix = round(df.drop(['Serial No.'],axis=1).corr(),2)
corr_matrix['Chance of Admit ']['GRE Score']

0.81

корреляцию между Chance of Admit и Research Experience

In [58]:
corr_matrix['Chance of Admit ']['Research']

0.55

корреляцию между GRE Scores и Research Experience

In [59]:
corr_matrix['GRE Score']['Research']

0.56

### Задание 2.11.3
Какой признак сильнее всех скоррелирован с целевым параметром?

В поле для ответа введите название признака, как оно указано в DataFrame

In [64]:
(corr_matrix - np.eye(len(corr_matrix)))['Chance of Admit '].abs().idxmax()

'CGPA'

### Задание 2.11.4
Постройте отдельно две матрицы корреляций признаков и целевой переменной: для соискателей, делавших исследования (Research=1) и для тех, у кого исследований нет (Research=0).

В каком случае признаки сильнее скоррелированы между собой?

In [72]:
Research_1 = df.drop(['Serial No.'],axis=1)[df.Research == 1].drop(['Research'],axis=1).corr()
Research_0 = df.drop(['Serial No.'],axis=1)[df.Research == 0].drop(['Research'],axis=1).corr()
Research_1 - Research_0

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           0.000000     0.143502           0.230024  0.241894   
TOEFL Score         0.143502     0.000000           0.106698  0.152873   
University Rating   0.230024     0.106698           0.000000  0.115630   
SOP                 0.241894     0.152873           0.115630  0.000000   
LOR                 0.077510    -0.034757           0.089619 -0.026822   
CGPA                0.128244     0.087399           0.175811  0.170653   
Chance of Admit     0.198612     0.164722           0.284513  0.238050   

                       LOR       CGPA  Chance of Admit   
GRE Score          0.077510  0.128244          0.198612  
TOEFL Score       -0.034757  0.087399          0.164722  
University Rating  0.089619  0.175811          0.284513  
SOP               -0.026822  0.170653          0.238050  
LOR                0.000000  0.002277          0.046030  
CGPA               0.002277  0.000000          0.139775  
Chance of Admit    0.046030  0.139775          0.000000

### Задание 2.11.5
В случае, когда корреляции между данными меньше, какие признаки наиболее скоррелированы с целевой переменной?

In [83]:
Research_0['Chance of Admit '].sort_values(ascending = False).index[1:3]

Index(['CGPA', 'TOEFL Score'], dtype='object')

### Задание 2.11.6
Постройте OLS регрессию `Chance of Admission ` на выбранные в предыдущей задаче признаки без стандартизации. Используйте данные для соискателей, у которых нет исследований (Research == 0). Признаки запишите в матрицу данных в том порядке, в котором они представлены в DataFrame.

Ответы округлите до 3 знаков после точки:

In [140]:
df_Research_0 = df[df.Research == 0]

A= np.column_stack((np.ones(506), CRIM, RM)

In [126]:
TOEFL_Score = df_Research_0['TOEFL Score']
CGPA = df_Research_0['CGPA']
A = np.column_stack((np.ones(len(df_Research_0)), TOEFL_Score, CGPA))
y = df_Research_0[['Chance of Admit ']]

In [136]:
ans = np.linalg.lstsq(A,y,rcond=None)[0].round(3)
ans

array([[-1.045],
       [ 0.004],
       [ 0.148]])

### Задание 2.11.7
Сделайте прогноз шансов поступления в университет для абитуриента с TOEFL Score=107, CGPA=9.1, используя модель, полученную в задаче 2.11.6 (используйте округленные значения признаков).

Ответ округлите до 2 знаков после точки:

In [139]:
Score = 107
CGPA = 9.1
predict = np.array([1,Score,CGPA]) @ ans
predict.round(2)

array([0.73])

### Задание 2.11.8
Аналогично задаче 2.11.6 постройте OLS регрессию Chance of Admission на выбранные в задаче 2.11.5 признаки, однако теперь сперва стандартизируйте эти признаки.

Ответы округлите до 2 знаков после точки:

In [142]:
Score = df_Research_0['TOEFL Score']
CGPA = df_Research_0['CGPA']
y = df_Research_0[['Chance of Admit ']]

In [153]:
Score_mean = Score.mean()
CGPA_mean = CGPA.mean()
y_mean = y.mean()

Score_c = Score - Score_mean
CGPA_c = CGPA - CGPA_mean
y_c = y - y_mean

Score_norm = np.linalg.norm(Score_c)
CGPA_norm = np.linalg.norm(CGPA_c)
y_norm = np.linalg.norm(y_c)

Score_st = Score_c / Score_norm
CGPA_st = CGPA_c / CGPA_norm
y_st = y_c / y_norm

A_st = np.column_stack((Score_st,CGPA_st))

In [156]:
np.linalg.lstsq(A_st,y_st, rcond=None)[0].round(2)

array([[0.19],
       [0.62]])

## 2.12. Линейный оператор

### Задание 2.12.2
рис Результат действия оператора на вектор называют образом вектора.

a) Найдите образ вектора $ v $ при действии оператора $ F $, если $ v = \left(\begin{array}{c} 1 \\ 2 \\ 3 \end{array}\right) $, а $ F =  \begin{pmatrix} 1 & 0 & 0 \\ 0 & 0 & 1 \\ 0 & -1 & 0 \end{pmatrix} $

		
Введите координаты полученного вектора через запятую (без пробела):

In [168]:
F = np.array([[1,0,0],[0,0,1],[0,-1,0]])
v = np.array([1,2,3]).reshape((3,1))

F @ v

array([[ 1],
       [ 3],
       [-2]])

### Задание 2.12.3
a) Найдите образы векторов $ u $ и $ v $ при действии оператора $ F $, 

если $ u = \left(\begin{array}{c} 1 \\ - 1 \end{array}\right) , v = \left(\begin{array}{c} 1 \\  1 \end{array}\right)$, а 
$F = \begin{pmatrix} 2 & 1 \\ 1 & 2 \end{pmatrix}$

Введите координаты полученных векторов через запятую (без пробела):

In [173]:
F = np.array([[2,1],[1,2]])
u = np.array([[1],[-1]])
v = np.array([[1],[1]])

In [172]:
display(F @ u, F @ v)

array([[ 1],
       [-1]])

array([[3],
       [3]])

## 2.13. Собственные векторы и числа

### Задание 2.13.3

Найдите собственные числа и вектора матрицы $ A = \begin{pmatrix} 5 & 1 \\ 1 & 5 \end{pmatrix} $

и ответьте на следующие вопросы:

а) Запишите собственные числа (сначала бОльшее по модулю, затем мЕньшее)

In [177]:
A = np.array([[5,1], [1,5]])
ans = np.linalg.eig(A)
ans[0]

array([6., 4.])

b) Какие векторы будут собственными для А?

In [178]:
ans[1]

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

## 2.16. Метод главных компонент, PCA

### Задание 2.16.5
Условие:
пусть $ x_1 = (1,2,1,1)^T,  x_2 = (70,130,60,65)^T, $ корреляционная матрица $
С = \begin{pmatrix} 1 & 0.9922 \\ 0.9922 & 1 \end{pmatrix} $


#### Задание 2.16.5_3
4) Выберите одну главную компоненту для дальнейшего анализа. Вычислите ее значения.

Введите компоненты с округлением до 4 знака после запятой.

In [218]:
C

array([[1.    , 0.9922],
       [0.9922, 1.    ]])

In [219]:
x_1 = np.array([[1,2,1,1]]).T
x_2 = np.array([[70,130,65,60]]).T
C = np.array([[1,0.9922],[0.9922,1]])

np.linalg.eig(C)

(array([1.9922, 0.0078]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [228]:
np.linalg.eig(C)[1]

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [220]:
display(x_1,x_2)

array([[1],
       [2],
       [1],
       [1]])

array([[ 70],
       [130],
       [ 65],
       [ 60]])

In [221]:
x_1_st = (x_1 - x_1.mean()) / np.linalg.norm((x_1 - x_1.mean()))
x_2_st = (x_2 - x_2.mean()) / np.linalg.norm((x_2 - x_2.mean()))

In [227]:
x_new_1 = (x_1_st + x_2_st)/np.linalg.norm(x_1_st + x_2_st)
(x_new_1).round(4)

array([[-0.244 ],
       [ 0.8643],
       [-0.2881],
       [-0.3323]])

In [198]:
np.sqrt(2)

1.4142135623730951