In [1]:
import numpy as np

In [2]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована

array([2.06902356e-316, 2.33648882e-307, 3.44900029e-307, 1.78250172e-312,
       0.00000000e+000])

In [3]:
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [4]:
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [5]:
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7

array([ 0,  7, 14])

In [8]:
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[9, 1, 5],
       [0, 4, 1],
       [1, 5, 3]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.shape(np.full((5,1), 1))

(5, 1)

In [15]:
np.shape(np.ones(5))

(5,)

In [20]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

In [21]:
np.arange(1, 14, 2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [23]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array[1][2]
a = (1,2)
my_array[a]
my_array[[[[[[[[[[1]]]]]]]]]]

array([[[[[[[[[10, 11, 12, 13]]]]]]]]])

In [54]:
my_array

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48]])

In [55]:
my_array[:,3]

array([ 4, 13, 48])

In [44]:
my_array[1]

array([10, 11, 12, 13])

In [45]:
my_array[:,1]

array([ 2, 11, 46])

In [49]:
my_array[1:,1:3]

array([[11, 12],
       [46, 47]])

Потренируемся извлекать из двумерного массива отдельные элементы и их срезы и производить над ними математические действия. Задания блока будем выполнять на примере массива, созданного кодом:

In [98]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [99]:
big_secret[:,:5]

array([[14.        , 10.        ,  6.        , 56.        , 40.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [ 0.        ,  1.        ,  4.        ,  9.        , 16.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [14.        , 10.        ,  6.        , 56.        , 40.        ]])

Пока мы не научились применять функции NumPy к массивам и их фрагментам, используйте цикл с параметром для организации вычислений.

#### Задание 1  
Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:

In [100]:
round(big_secret[:,-1:].sum(),2)

3154.33

#### Задание 2  
Выделите из каждой строки массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Округлите ответ до двух цифр после запятой:

In [101]:
diag_sum = 0
for i in range(5): diag_sum += big_secret[:,:5][i,i]
round(diag_sum,2)

121.37

In [102]:
round(big_secret.diagonal().sum(),2)

121.37

#### Задание 3   
Выделите из каждой строки массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [103]:
big_secret[:,-5:].diagonal().prod()

341505315559.2347

In [104]:
# *****************************************************************************

In [105]:
my_array = np.random.randint(1, 100, (4, 6)) 
my_array

array([[50, 11, 84, 75, 49, 81],
       [ 4, 86, 19, 91, 84, 16],
       [90, 89, 34, 88, 68, 21],
       [31, 57, 86, 53, 59, 29]])

In [106]:
my_slice = my_array[1:3, 2:4]
my_slice

array([[19, 91],
       [34, 88]])

In [107]:
my_slice[:] = 0
my_array

array([[50, 11, 84, 75, 49, 81],
       [ 4, 86,  0,  0, 84, 16],
       [90, 89,  0,  0, 68, 21],
       [31, 57, 86, 53, 59, 29]])

Упражнения
Проверим знания! Продолжим работать с массивом big_secret. Замените на 1 все элементы, у которых оба индекса нечётные, и на -1 все элементы, у которых оба индекса чётные.

In [109]:
for i in range(np.shape(big_secret)[0]):
    for j in range(np.shape(big_secret)[1]):
        if i%2 & j%2: big_secret[i,j] = 1
        elif ~i%2 & ~j%2: big_secret[i,j] = -1


#### Задание 4   
Выделите из каждой строки обновлённого массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Введите полученный ответ без изменений и округлений.

In [114]:
big_secret[:,:5].diagonal().sum()

-1.0

#### Задание 5  
Выделите из каждой строки обновлённого массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [115]:
big_secret[:,-5:].diagonal().prod()

-1.0

In [120]:
# **************************************************************************************

In [121]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число:{}'
      .format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число:[ 6 12 18]


In [139]:
dd = np.empty_like(result4)
ff = np.empty_like(result4)

In [137]:
d,f = np.modf(result4)

In [142]:
my_array = np.random.randint(0, 10, 20)
my_array

array([5, 9, 7, 7, 5, 7, 7, 8, 0, 6, 1, 4, 9, 1, 6, 3, 1, 3, 7, 6])

In [143]:
my_array.reshape((4,5))

array([[5, 9, 7, 7, 5],
       [7, 7, 8, 0, 6],
       [1, 4, 9, 1, 6],
       [3, 1, 3, 7, 6]])

In [151]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array.flatten()

(9,)

In [154]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array.reshape(9)

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [156]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[9, 8, 4, 2],
       [1, 0, 5, 9],
       [3, 8, 9, 8]])

In [157]:
my_array<5

array([[False, False,  True,  True],
       [ True,  True, False, False],
       [ True, False, False, False]])

In [158]:
my_array[my_array<5]

array([4, 2, 1, 0, 3])

In [160]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[9, 4],
       [1, 5],
       [3, 9]])

In [161]:
my_array = np.random.randint(0, 10, (4, 6))
my_array

array([[8, 1, 2, 9, 9, 3],
       [4, 7, 8, 2, 8, 9],
       [6, 1, 3, 2, 3, 1],
       [1, 2, 3, 4, 0, 2]])

In [162]:
np.sort(my_array, axis=1)

array([[1, 2, 3, 8, 9, 9],
       [2, 4, 7, 8, 8, 9],
       [1, 1, 2, 3, 3, 6],
       [0, 1, 2, 2, 3, 4]])

In [163]:
np.sort(my_array, axis=0)

array([[1, 1, 2, 2, 0, 1],
       [4, 1, 3, 2, 3, 2],
       [6, 2, 3, 4, 8, 3],
       [8, 7, 8, 9, 9, 9]])

#### Упражнения  
Для выполнения упражнений из следующего блока мы будем использовать массив, созданный с помощью кода:

In [167]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

#### Задание 1  
Сколько столбцов содержит массив great_secret?

In [169]:
np.shape(great_secret)[1]

3

#### Задание 2  
Чему равна сумма косинусов элементов первой строки массива great_secret? Ответ округлите до двух знаков после запятой.

In [175]:
round(np.cos(great_secret[0]).sum(),2)

0.16

#### Задание 3  
Чему равна сумма элементов массива great_secret, значение которых больше 50?

In [177]:
great_secret[great_secret > 50].sum()

5470.0

#### Задание 4   
Переведите массив great_secret в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150? Скопируйте ответ из Jupyter Notebook без изменений.

In [183]:
great_secret.flatten()[150]

7.0710678118654755

#### Задание 5  
Отсортируйте значения столбцов массива great_secret по возрастанию. Чему равна сумма элементов последней строки отсортированного массива? Ответ округлите до двух цифр после запятой.

In [190]:
round(np.sort(great_secret,axis=0)[-1].sum(),2)

115.12

In [2]:
# ********************************************************************************

ID (номер в журнале)	Рост, см	Масса тела, кг	Средний балл  
1	135	34	4  
2	160	43	5  
3	163	40	4.3  
4	147	44	5  
5	138	41	4.7  
6	149	54	3.9  
7	136	39	4.2  
8	154	48	4.9  
9	137	35	3.7  
10	165	60	4.6  

Создайте массив, содержащий эти данные, и сохраните его под именем students.

In [3]:
import pandas as pd

In [4]:
df_students = pd.read_csv('students.csv',sep='\t', encoding = 'windows-1251')

In [5]:
df_students

ID (номер в журнале)  Рост, см  Масса тела, кг  Средний балл
0                     1       135              34           4.0
1                     2       160              43           5.0
2                     3       163              40           4.3
3                     4       147              44           5.0
4                     5       138              41           4.7
5                     6       149              54           3.9
6                     7       136              39           4.2
7                     8       154              48           4.9
8                     9       137              35           3.7
9                    10       165              60           4.6

In [6]:
students = df_students.values
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [7]:
# Среднее арифметическое (mean) — сумма всех значений, делённая на их количество, показывает 
# общую тенденцию данных и описывает их одним числом. 
# Узнаем среднюю успеваемость школьников в классе, используя функцию mean:
mean = np.mean(students[:,-1])
mean

4.430000000000001

In [8]:
median = np.median(students[:,-1])
median


4.449999999999999

#### Задание 1
Чему равно медианное значение массы тела школьников?

In [12]:
np.median(students[:,2])

42.0

#### Задание 2
На сколько среднее арифметическое массы тела школьников больше медианного значения для этого же показателя? Дайте ответ в килограммах с точностью до одной десятой кг.

In [14]:
round(np.mean(students[:,2]) - np.median(students[:,2]),1)

1.8

In [ ]:
# ***********************************************************************************

In [15]:
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

#### Задание 3
Между какой парой признаков в массиве students наблюдается минимальная корреляция?

In [18]:
np.corrcoef(students[:,1:], rowvar=False)

array([[1.        , 0.64314431, 0.46293714],
       [0.64314431, 1.        , 0.29801325],
       [0.46293714, 0.29801325, 1.        ]])

In [20]:
# ***************************************************************************

In [21]:
std = np.std(students[:,1])
std

11.083320801997928

#### Задание 4
Используя имеющийся набор данных о школьниках, найдите, чему равно стандартное отклонение их средних баллов.

In [22]:
np.std(students[:,3])

0.4517742799230607

#### Задание 5
Посчитайте, чему равна дисперсия значений веса школьников.

Эту величину можно получить двумя способами: математически - используя определение дисперсии и известную функцию в блоке, или самостоятельно - используя подходящую функцию модуля NumPy.

In [24]:
np.std(students[:,2])**2

60.36